<header class="page-heading page-heading--form"><div><a class="back-link" href="/mantenedores?proceso_id=<?= $view->escape($valor['proceso_id'] ?? '') ?>">← Volver a mantenedores</a><p class="eyebrow">Administración de <?= $kind ?></p><h1><?= $view->escape($title) ?></h1><p class="muted">Los formularios clínicos utilizarán este valor como una opción controlada.</p></div></header>
<?php if(!empty($errors['general'][0])):?><div class="alert alert--error"><?= $view->escape($errors['general'][0]) ?></div><?php endif; ?>
<form class="record-form catalog-form" method="post" action="<?= $view->escape($action) ?>"><?= $view->csrfField() ?><?php if($method!=='POST'):?><input type="hidden" name="_method" value="<?= $view->escape($method) ?>"><?php endif;?>
<section class="form-section"><div class="form-section__heading"><span>1</span><div><h2>Identificación del valor</h2><p>Código técnico estable y nombre visible.</p></div></div><div class="form-grid">
<label class="field"><span>Proceso *</span><select name="proceso_id" required><?php foreach($procesos as $proceso):?><option value="<?= $view->escape($proceso['id']) ?>" <?= (string)($valor['proceso_id']??'')===(string)$proceso['id']?'selected':'' ?>><?= $view->escape($proceso['nombre']) ?></option><?php endforeach;?></select></label>
<label class="field"><span>Orden</span><input type="number" name="orden" min="0" max="65535" value="<?= $view->escape($valor['orden']??0) ?>"></label>
<label class="field"><span>Código *</span><input name="codigo" maxlength="50" required value="<?= $view->escape($valor['codigo']??'') ?>" placeholder="EJEMPLO_CODIGO"><small>Mayúsculas, números y guion bajo.</small></label>
<label class="field"><span>Nombre visible *</span><input name="nombre" maxlength="100" required value="<?= $view->escape($valor['nombre']??'') ?>" placeholder="Nombre que verá la familia"></label>
<?php if($kind==='estados'): ?><label class="field color-field"><span>Color del estado *</span><span class="color-input"><input type="color" name="color" required value="<?= $view->escape($valor['color']??'#64748B') ?>"><strong data-color-value><?= $view->escape(strtoupper($valor['color']??'#64748B')) ?></strong></span><small>Se utilizará en calendarios y etiquetas.</small></label><?php endif; ?>
<label class="check-field field--wide"><input type="checkbox" name="activo" value="1" <?= !empty($valor['activo'])?'checked':'' ?>><span>Disponible en los formularios</span></label>
</div></section><div class="form-actions"><a class="button button--secondary" href="/mantenedores?proceso_id=<?= $view->escape($valor['proceso_id']??'') ?>">Cancelar</a><button class="button button--primary" type="submit">Guardar valor</button></div></form>
