<header class="page-heading"><div><p class="eyebrow">Administración</p><h1>Mantenedores</h1><p class="muted">Controla los estados y tipos disponibles en cada proceso.</p></div></header>
<?php if($message=$view->flash('success')):?><div class="alert alert--success"><?= $view->escape($message) ?></div><?php endif; ?>
<?php if($message=$view->flash('error')):?><div class="alert alert--error"><?= $view->escape($message) ?></div><?php endif; ?>

<section class="process-tabs" aria-label="Procesos"><?php foreach($procesos as $item): ?><a class="process-tab <?= (int)($proceso['id'] ?? 0)===(int)$item['id']?'is-active':'' ?>" href="/mantenedores?proceso_id=<?= $view->escape($item['id']) ?>"><span><?= $view->escape($item['codigo']) ?></span><strong><?= $view->escape($item['nombre']) ?></strong><small><?= $view->escape($item['total_estados']) ?> estados · <?= $view->escape($item['total_tipos']) ?> tipos</small></a><?php endforeach; ?></section>

<?php if($proceso): ?>
<header class="catalog-heading"><div><p class="eyebrow">Proceso seleccionado</p><h2><?= $view->escape($proceso['nombre']) ?></h2><p><?= $view->escape($proceso['codigo']) ?></p></div></header>

<?php foreach(['estados'=>$estados,'tipos'=>$tipos] as $kind=>$items): ?>
<section class="catalog-panel"><div class="catalog-panel__heading"><div><h2><?= $kind==='estados'?'Estados':'Tipos' ?></h2><p>Valores controlados para evitar entradas libres o duplicadas.</p></div><a class="button button--compact button--primary" href="/mantenedores/<?= $kind ?>/create?proceso_id=<?= $view->escape($proceso['id']) ?>">Agregar <?= $kind==='estados'?'estado':'tipo' ?></a></div>
<?php if($items===[]): ?><div class="catalog-empty">Este proceso no utiliza <?= $kind ?>.</div><?php else: ?><div class="catalog-table"><div class="catalog-table__head"><span>Orden</span><span>Código y nombre</span><span>Estado</span><span>Acciones</span></div><?php foreach($items as $item): ?><div class="catalog-table__row"><span class="order-chip"<?= $kind==='estados'?' style="--catalog-color:'.$view->escape($item['color']).'"':'' ?>><?= $view->escape($item['orden']) ?></span><div><strong><?= $view->escape($item['nombre']) ?></strong><small><?= $view->escape($item['codigo']) ?><?= $kind==='estados'?' · '.$view->escape($item['color']):'' ?></small></div><span class="status <?= $item['activo']?'status--activo':'status--finalizado' ?>"><?= $item['activo']?'Activo':'Inactivo' ?></span><div class="catalog-actions"><a href="/mantenedores/<?= $kind ?>/<?= $view->escape($item['id']) ?>/edit">Editar</a><form method="post" action="/mantenedores/<?= $kind ?>/<?= $view->escape($item['id']) ?>/toggle"><?= $view->csrfField() ?><input type="hidden" name="_method" value="PUT"><button type="submit"><?= $item['activo']?'Desactivar':'Activar' ?></button></form><form method="post" action="/mantenedores/<?= $kind ?>/<?= $view->escape($item['id']) ?>" onsubmit="return confirm('¿Eliminar este valor? Solo será posible si no está utilizado.')"><?= $view->csrfField() ?><input type="hidden" name="_method" value="DELETE"><button class="danger-link" type="submit">Eliminar</button></form></div></div><?php endforeach; ?></div><?php endif; ?></section>
<?php endforeach; ?>
<?php endif; ?>
