<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FamiliaController;
use App\Http\Controllers\PersonaController;
use App\Http\Controllers\AtencionController;
use App\Http\Controllers\MedicamentoController;
use App\Http\Controllers\DocumentoController;
use App\Http\Controllers\MantenedorController;
use App\Http\Controllers\PersonaContextController;
use App\Http\Controllers\InvitacionController;

$router->get('/', [DashboardController::class, 'index'])->middleware(['auth']);
$router->get('/familias', [FamiliaController::class, 'index'])->middleware(['auth']);
$router->get('/familias/create', [FamiliaController::class, 'create'])->middleware(['auth']);
$router->post('/familias', [FamiliaController::class, 'store'])->middleware(['auth', 'csrf']);
$router->post('/familias/{id}/seleccionar', [FamiliaController::class, 'select'])->middleware(['auth', 'csrf']);
$router->put('/familias/{id}/archivar', [FamiliaController::class, 'archive'])->middleware(['auth', 'csrf']);
$router->put('/familias/{id}/restaurar', [FamiliaController::class, 'restore'])->middleware(['auth', 'csrf']);
$router->get('/familias/integrantes', [FamiliaController::class, 'members'])->middleware(['auth', 'family']);
$router->post('/familias/integrantes', [FamiliaController::class, 'addMember'])->middleware(['auth', 'family', 'csrf']);
$router->put('/familias/integrantes/{id}/rol', [FamiliaController::class, 'updateMemberRole'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->post('/familias/invitaciones', [InvitacionController::class, 'create'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->put('/familias/invitaciones/{id}/revocar', [InvitacionController::class, 'revoke'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->get('/invitaciones/aceptar', [InvitacionController::class, 'show']);
$router->post('/invitaciones/aceptar', [InvitacionController::class, 'accept'])->middleware(['auth', 'csrf']);
$router->get('/personas', [PersonaController::class, 'index'])->middleware(['auth', 'family']);
$router->get('/personas/create', [PersonaController::class, 'create'])->middleware(['auth', 'family']);
$router->post('/personas', [PersonaController::class, 'store'])->middleware(['auth', 'family', 'csrf']);
$router->get('/personas/{id}', [PersonaController::class, 'show'])->middleware(['auth', 'family']);
$router->get('/personas/{id}/edit', [PersonaController::class, 'edit'])->middleware(['auth', 'family']);
$router->put('/personas/{id}', [PersonaController::class, 'update'])->middleware(['auth', 'family', 'csrf']);
$router->post('/persona-activa', [PersonaContextController::class, 'select'])->middleware(['auth', 'family', 'csrf']);
$router->get('/atenciones', [AtencionController::class, 'index'])->middleware(['auth', 'family']);
$router->get('/atenciones/create', [AtencionController::class, 'create'])->middleware(['auth', 'family']);
$router->post('/atenciones', [AtencionController::class, 'store'])->middleware(['auth', 'family', 'csrf']);
$router->get('/atenciones/{id}', [AtencionController::class, 'show'])->middleware(['auth', 'family']);
$router->get('/atenciones/{id}/edit', [AtencionController::class, 'edit'])->middleware(['auth', 'family']);
$router->put('/atenciones/{id}', [AtencionController::class, 'update'])->middleware(['auth', 'family', 'csrf']);
$router->get('/medicamentos', [MedicamentoController::class, 'index'])->middleware(['auth', 'family']);
$router->get('/medicamentos/create', [MedicamentoController::class, 'create'])->middleware(['auth', 'family']);
$router->post('/medicamentos', [MedicamentoController::class, 'store'])->middleware(['auth', 'family', 'csrf']);
$router->get('/medicamentos/{id}', [MedicamentoController::class, 'show'])->middleware(['auth', 'family']);
$router->get('/medicamentos/{id}/edit', [MedicamentoController::class, 'edit'])->middleware(['auth', 'family']);
$router->put('/medicamentos/{id}', [MedicamentoController::class, 'update'])->middleware(['auth', 'family', 'csrf']);
$router->get('/documentos', [DocumentoController::class, 'index'])->middleware(['auth', 'family']);
$router->get('/documentos/create', [DocumentoController::class, 'create'])->middleware(['auth', 'family']);
$router->post('/documentos', [DocumentoController::class, 'store'])->middleware(['auth', 'family', 'csrf']);
$router->get('/documentos/{id}/download', [DocumentoController::class, 'download'])->middleware(['auth', 'family']);
$router->get('/documentos/{id}/preview', [DocumentoController::class, 'preview'])->middleware(['auth', 'family']);
$router->delete('/documentos/{id}', [DocumentoController::class, 'destroy'])->middleware(['auth', 'family', 'csrf']);
$router->get('/mantenedores', [MantenedorController::class, 'index'])->middleware(['auth', 'family', 'admin']);
$router->get('/mantenedores/{kind}/create', [MantenedorController::class, 'create'])->middleware(['auth', 'family', 'admin']);
$router->post('/mantenedores/{kind}', [MantenedorController::class, 'store'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->get('/mantenedores/{kind}/{id}/edit', [MantenedorController::class, 'edit'])->middleware(['auth', 'family', 'admin']);
$router->put('/mantenedores/{kind}/{id}', [MantenedorController::class, 'update'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->put('/mantenedores/{kind}/{id}/toggle', [MantenedorController::class, 'toggle'])->middleware(['auth', 'family', 'admin', 'csrf']);
$router->delete('/mantenedores/{kind}/{id}', [MantenedorController::class, 'destroy'])->middleware(['auth', 'family', 'admin', 'csrf']);
