CREATE TABLE estados (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  proceso_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(50) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  orden SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uk_estados_proceso_codigo UNIQUE (proceso_id, codigo),
  CONSTRAINT uk_estados_proceso_nombre UNIQUE (proceso_id, nombre),
  CONSTRAINT fk_estados_proceso FOREIGN KEY (proceso_id) REFERENCES procesos(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
