CREATE TABLE atenciones (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  persona_id BIGINT UNSIGNED NOT NULL,
  tipo_id BIGINT UNSIGNED NOT NULL,
  estado_id BIGINT UNSIGNED NOT NULL,
  registrado_por_usuario_id BIGINT UNSIGNED NOT NULL,
  fecha_hora DATETIME NOT NULL,
  profesional VARCHAR(150) NULL,
  especialidad VARCHAR(120) NULL,
  centro_medico VARCHAR(150) NULL,
  motivo TEXT NULL,
  diagnostico_resultado TEXT NULL,
  indicaciones TEXT NULL,
  temas_abordados TEXT NULL,
  acuerdos TEXT NULL,
  proxima_fecha DATE NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_atenciones_persona_fecha (persona_id, fecha_hora),
  KEY idx_atenciones_tipo (tipo_id),
  KEY idx_atenciones_estado (estado_id),
  KEY idx_atenciones_usuario (registrado_por_usuario_id),
  CONSTRAINT fk_atenciones_persona FOREIGN KEY (persona_id) REFERENCES personas(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_atenciones_tipo FOREIGN KEY (tipo_id) REFERENCES tipos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_atenciones_estado FOREIGN KEY (estado_id) REFERENCES estados(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_atenciones_usuario FOREIGN KEY (registrado_por_usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
