CREATE TABLE documentos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  persona_id BIGINT UNSIGNED NOT NULL,
  atencion_id BIGINT UNSIGNED NULL,
  medicamento_id BIGINT UNSIGNED NULL,
  tipo_id BIGINT UNSIGNED NOT NULL,
  subido_por_usuario_id BIGINT UNSIGNED NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  archivo_ruta VARCHAR(500) NOT NULL,
  mime_type VARCHAR(100) NOT NULL,
  fecha_documento DATE NULL,
  descripcion TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uk_documentos_archivo_ruta UNIQUE (archivo_ruta),
  KEY idx_documentos_persona_fecha (persona_id, fecha_documento),
  KEY idx_documentos_atencion (atencion_id),
  KEY idx_documentos_medicamento (medicamento_id),
  KEY idx_documentos_tipo (tipo_id),
  KEY idx_documentos_usuario (subido_por_usuario_id),
  CONSTRAINT fk_documentos_persona FOREIGN KEY (persona_id) REFERENCES personas(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_documentos_atencion FOREIGN KEY (atencion_id) REFERENCES atenciones(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_documentos_medicamento FOREIGN KEY (medicamento_id) REFERENCES medicamentos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_documentos_tipo FOREIGN KEY (tipo_id) REFERENCES tipos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_documentos_usuario FOREIGN KEY (subido_por_usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
