CREATE TABLE familia_invitaciones (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  familia_id BIGINT UNSIGNED NOT NULL,
  tipo_rol_id BIGINT UNSIGNED NOT NULL,
  estado_id BIGINT UNSIGNED NOT NULL,
  token_hash CHAR(64) NOT NULL,
  expira_at DATETIME NOT NULL,
  creada_por_usuario_id BIGINT UNSIGNED NOT NULL,
  aceptada_por_usuario_id BIGINT UNSIGNED NULL,
  aceptada_at DATETIME NULL,
  revocada_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT uk_familia_invitaciones_token UNIQUE (token_hash),
  KEY idx_invitaciones_familia_estado (familia_id, estado_id, expira_at),
  KEY idx_invitaciones_rol (tipo_rol_id),
  KEY idx_invitaciones_creador (creada_por_usuario_id),
  KEY idx_invitaciones_aceptada_por (aceptada_por_usuario_id),
  CONSTRAINT fk_invitaciones_familia FOREIGN KEY (familia_id) REFERENCES familias(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invitaciones_rol FOREIGN KEY (tipo_rol_id) REFERENCES tipos(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invitaciones_estado FOREIGN KEY (estado_id) REFERENCES estados(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invitaciones_creador FOREIGN KEY (creada_por_usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_invitaciones_aceptada_por FOREIGN KEY (aceptada_por_usuario_id) REFERENCES usuarios(id) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
